# Generated by Django 2.0.6 on 2018-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20180626_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
